# -*- coding: utf-8 -*-
"""E_mail_spammer_for_others_Kazushi_Lambert (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZSwiAc3fFTQo_FR49XuxANkqGP1fr5H
"""

list_of_email = []

#Inside of this array ONLY put string format e-mail addresses
#It should look like this "email_name@somethingmail.com"
#If there are multiple please separate them with commas
#Example : ["email1@gmail.com","email2@hotmail.com","email3@avast.com"]
#You can put as many e-mail as you want

#Don't forget to run the code block that defines list_of_email before running this code block or it'll result in an error because the computer doesnt know what list_of_email is

#Potential errors :
    #Wrong password/email adress (duh)
    #Wrong gmail port
    #Text not ascii compatible : accented, special, arabic, asian characters are not supported sometimes ' doesn't work neither so just erase and rewrite (it's complicated)
    #Wrong format for all inputs
    #Wrong format for list_of_email

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.header import Header
message = MIMEMultipart("alternative")

my_email= "example@ABC.com"
#Input your email here

password_key= "passwordExample"
#Input your password here, do not worry it is secure, you can check the code to see what is done with your information

message['Subject'] = "subjectExample"
#Insert the e-mail's subject here

text_content= "textExample"
#Input your text content here
#Everything should be one one singular line
#if you want to skip a line type \n
#Example : "Hi,\n\nhow are you doing? We should meet again!\nMaybe coffee?\n\n Patricia GenericFamilyName" would give (without the # of course):
#
#Hi,
#
#how are you doing? We should meet again!
#Maybe coffee?
#
#Patricia GenericFamilyName

gmail_port= 587
#this can sometimes change depending on the machine, if everyother troubleshoot doesn't work try changing it to 465

gmail_server= "smtp.gmail.com"
my_server = smtplib.SMTP(gmail_server, gmail_port)
my_server.ehlo()
my_server.starttls()
my_server.login(my_email, password_key)
message.attach(MIMEText(text_content))

for i in range(len(list_of_email)):
    my_server.sendmail(my_email, list_of_email[i], message.as_string())
my_server.quit()

